### ISSUE TITLE
Missing Storage permission on Marshmallow

### ISSUE THREAD

**Issue by walrus543** [xdevs23/Cornowser#10]
Hi,
I can't download a file "no permission to write, abort".
Cornowser (1.0.4.1) doesn't ask the Storage permission so we have to grant it manually.

Thank you
![unnamed](https://cloud.githubusercontent.com/assets/5938828/12840321/af39e406-cbe2-11e5-896a-451a3c50f63a.png)
![unnamed 1](https://cloud.githubusercontent.com/assets/5938828/12840322/af3c588a-cbe2-11e5-96ac-ed3719baf37f.png)

Nexus 5 - CM13 based rom - Android 6.0.1

**Comment by xdevs23** [comment]
Thank you very much. I  will try to fix that, too.

**Comment by xdevs23** [comment]
Ok I fixed it in the latest commit. Wait for the next release :smiley:

**Comment by walrus543** [comment]
Thanks mate :-)

**Comment by xdevs23** [comment]
No problem. Is it working now for you?

**Comment by walrus543** [comment]
Yep. I have the request pop-up now.

**Comment by xdevs23** [comment]
Great. Thank you for your feedback!
