### ISSUE TITLE
FC using Cornowser (background)

### ISSUE THREAD

**Issue by walrus543** [xdevs23/Cornowser#29]
Hi,
I opened a link from Pushbullet with Cornowser (background). A few seconds later, I opened the Cornowser app and I had a FC.
I have attached a log.

Thank you.
[logcat_and_device_info.zip](https://github.com/xdevs23/Cornowser/files/165133/logcat_and_device_info.zip)

**Comment by xdevs23** [comment]
Thanks, that bug is already known, I will try to fix it but not sure when it is going to work correctly. The feature is still experimental...
Also I usually don't need logs on crashes anymore because Crashlytics will report them automatically.

**Comment by walrus543** [comment]
You should probably remove it until it's fixed. It takes one (useless) line in the popup resolver window.
Could you add an option to be able to opt ouf of those crash reports? I prefer uploading a file to suffer automatic crash reports.
Otherwise you could add a popup to ask our permission (like Firefox).

**Comment by xdevs23** [comment]
Yes I will try to add such an option to the settings. Hence it is better and easier for me when having automatic crash reports (so I don't need logcat and stuff and I can have a better overwiew), I integrated it. But ok, I also respect your opinion and I am going to add that if possible. Thanks.

**Comment by walrus543** [comment]
Great, thank you.

**Comment by xdevs23** [comment]
Great news! I fixed background loading!! I took some time to overwiew the problem and I finally found a working solution :D

**Comment by xdevs23** [comment]
I also integrated the Crashlytics opt-out feature right now. Wait for the update :)

**Comment by walrus543** [comment]
Nice job mate! Thanks for taking into account the point of view of your users :)

**Comment by xdevs23** [comment]
No problem :D
