### ISSUE TITLE
Error loading a web page

### ISSUE THREAD

**Issue by walrus543** [xdevs23/Cornowser#3]
Hi,
I can't access to this [web page](http://android.stackexchange.com/questions/125368/how-to-check-what-apps-are-running-in-android-6-0). No issue with Aurora browser.
I have attached a screenshot and a log.

Thanks.
[logcat_and_device_info.zip](https://github.com/xdevs23/Cornowser/files/117520/logcat_and_device_info.zip)

**Comment by xdevs23** [comment]
Thank you very much. I checked the error and I know what is causing it.
The website is trying to open up the StackExchange app.
But the intent handling in Cornowser seems to not be working correctly.
I am going to try to fix that.

**Comment by walrus543** [comment]
No prob, thank you.

**Comment by xdevs23** [comment]
This is fixed now as well. Wait for next release.
