### ISSUE TITLE
Lastes 1.0.5.6 will flash on page load or change

### ISSUE THREAD

**Issue by fishg** [xdevs23/Cornowser#31]
Latest 1.0.5.6 will flash on page load or change.

system version: zui 1.6.320
android version: 6.0.1

**Comment by walrus543** [comment]
Same issue here. Nexus 5 Android 6.0.1

**Comment by xdevs23** [comment]
Yeah, I saw this too. I'm sorry about this. Will be fixed today maybe.

**Comment by xdevs23** [comment]
Ok so now the problem seems to be fixed, I will release an update now.

**Comment by walrus543** [comment]
Thanks for the quick fix!

**Comment by xdevs23** [comment]
Yeah no problem, is now fixed :D

**Comment by fishg** [comment]
Thanks.

**Comment by xdevs23** [comment]
You're welcome
