### ISSUE TITLE
How did you implement the omnibox show/hide animation effect when scrolling the webview ?

### ISSUE THREAD

**Issue by gaoflow** [xdevs23/Cornowser#37]
Hi, I'm so confuse about how did you implement the omnibox show/hide animation effect when scrolling the webview. 

How to make both webview and omnibox listening the OnTouchListener?

When webview at the top, how to make omnibox not overlay the webview? ( I saw omnibox and webview are just like positioned  in a linearlayout) And when I scroll the webview, how to make both omnibox and webview scroll at the same speed until omnibox disappeared?

I really need your help, thx!

**Comment by xdevs23** [comment]
The scrolling inside the webview is handled by the view itself. You just need to set a OnClickListener to the webview and make the omnibox to move.
Look into the source code if you want to know it. It is located here: http://github.com/xdevs23/Cornowser/blob/master/app/src/main/java/io/xdevs23/cornowser/browser/browser/modules/ui/OmniboxAnimations.java
