### ISSUE TITLE
Unable to save a picture

### ISSUE THREAD

**Issue by walrus543** [xdevs23/Cornowser#49]
Hi,
I can't save this picture: [http://www.servimg.com/view/19470175/2](http://www.servimg.com/view/19470175/2)
No pop up with a long press

Mods => Xposed: BubbleUpnP, CrappaLinks, FakeGapps, XposedGmsCoreUnifiedNlp, Xprivacy
Cornowser version 1.0.7.7
Nexus 5
Android 6.0.1
Chipset ARMv7

How to reproduce the bug:
1. Open the above link
2. Long press on the picture
3. Nothing happens

**Comment by xdevs23** [comment]
Yes some pictures don't get saved because they are not recognized as such.
The self-made long press feature is not so intelligent yet.
But thanks for the report!!

**Comment by xdevs23** [comment]
Maybe this will be solved soon ...

**Comment by xdevs23** [comment]
Fixed.
