### ISSUE TITLE
Firefox Sync API 

### ISSUE THREAD

**Issue by MaluNoPeleke** [xdevs23/Cornowser#54]
Can you please add Firefox Sync API for synchronization?
https://wiki.mozilla.org/Services/Sync

**Comment by xdevs23** [comment]
Yeah, I will try it, thanks for telling about this.

**Comment by xdevs23** [comment]
I don't think that I can implement this, I can't be hosting my own firefox sync server for this.

**Comment by xdevs23** [comment]
Won't add (for now)
