### ISSUE TITLE
Crosswalk 

### ISSUE THREAD

**Issue by dorcusmafia** [xdevs23/Cornowser#55]
I can't use the included sh installer script on Windows, I tried using win-bash to run it but I'm still getting the build error of missing dependencies (org.xwalk:xwalk_core_library_canary:21.51.542.0) Is there a way that I could manually install the dependencies? Or a fix for Windows?

**Comment by xdevs23** [comment]
You need to run `configure.sh` first to install crosswalk dependencies. Also make sure that you have the `mvn` command available.

**Comment by xdevs23** [comment]
You can also view a guide here: [Building Cornowser](https://github.com/xdevs23/Cornowser/wiki/Building-Cornowser)
