### ISSUE TITLE
Do you have proxy support?

### ISSUE THREAD

**Issue by cubanitoalex** [xdevs23/Cornowser#60]
Do you have proxy support? Manual Proxy within the app

**Comment by xdevs23** [comment]
No, not yet

**Comment by cubanitoalex** [comment]
It would be good to include it as a suggestion to you as a developer...Many private networks use proxy to exit.

**Comment by flakomix** [comment]
It would be good to include it as a suggestion to you as a developer...Many private networks use proxy to exit.

**Comment by xdevs23** [comment]
Well yeah I'm very busy at the moment, not sure when that is gonna be implemented.
