### ISSUE TITLE
Do you faced this crash?

### ISSUE THREAD

**Issue by davidbilly** [xdevs23/Cornowser#61]
HI @xdevs23 sorry for trouble you. Do you have faced this following crash? while using crosswalk as webview.

null exception when getNavigationHistory()?

Thanks!

Impacted Cases
------------------
1)  Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.xwalk.core.XWalkNavigationHistory.canGoForward()' on a null object reference
at CustomWebView.canGoForward(CustomWebView.java:398)

The CustomWebView was extends XWalkView class

2)  Caused by java.lang.NullPointerException at getNavigationHistory()

The CustomWebView was extends XWalkView class

3)  Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int org.xwalk.core.internal.XWalkNavigationHistoryInternal.size()' on a null object reference
at org.xwalk.core.internal.XWalkContentsClientBridge$1.handleMessage(XWalkContentsClientBridge.java:131)

Reproduce Test Steps
--------------------------

Just some certain phone will crash.

Devices list :
Samsung SM-J700F 
Samsung SM-G531H
Samsung GT-I9152
Sony D2533
Sony E5353
Sony SO-01G
Sony SOV31
HUAWEI TIT-AL00
Lenovo A7020a48
Samsung SM-G530BT
Samsung SM-G900F

Expected Outcome
----------------------

Wont crash

Actual Outcome
----------------------

App Crash.

Test Case Source Code
----------------------

1)  for (int i = 0; i < getNavigationHistory().size(); i++)
clearCacheForSingleFile(getNavigationHistory().getItemAt.getUrl());
// Clear the history
getNavigationHistory().clear();

2) getNavigationHistory().canGoForward()
getNavigationHistory().canGoBack()

3)  etNavigationHistory().navigate(XWalkNavigationHistory.Direction.FORWARD, steps);

Reference : https://crosswalk-project.org/jira/browse/XWALK-7474

**Comment by xdevs23** [comment]
Hmm, I don't think that I ever got that crash, but I'm actually busy with other things and barely get time to work on this project...

**Comment by davidbilly** [comment]
@xdevs23 i see, thanks ya :)

**Comment by xdevs23** [comment]
I hope I don't forget to check this out, I'll let you know when I get time to do this.

**Comment by davidbilly** [comment]
@xdevs23 sure, take your time :D i suspect this issue due to open new tab/pop up when initial webview :( just random devices having this issue lol
